services:
  front:
    container_name: spacerework-front-container
    build:
      context: . # Chemin du répertoire où se trouve le Dockerfile
      dockerfile: Dockerfile
    image: spacerework-front-image
    ports:
      - "5173:5173"
    volumes:
      # Les volumes sont montés lors du démarrage du conteneur
      # mais avant les commandes CMD / ENTRYPOINT
      - ./public:/app/public
      - ./src:/app/src
      - ./tests:/app/tests
    tty: true